### ISSUE TITLE
Error in upload trigger

### ISSUE THREAD

**Issue by Bharath-2656** [aws-samples/serverless-pdf-chat#3]
I tried deploying the code and tested out by uploading a document.
The document was uploaded to S3 but the upload trigger function throws error, as head object not found

Logs:

[ERROR] ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/logging/logger.py", line 441, in decorate
    return lambda_handler(event, context, *args, **kwargs)
  File "/var/task/main.py", line 31, in lambda_handler
    s3.download_file(BUCKET, key, f"/tmp/{file_name}")
  File "/var/task/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/var/task/boto3/s3/transfer.py", line 326, in download_file
    future.result()
  File "/var/task/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/var/task/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/var/task/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/var/task/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/var/task/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by allenrwhite** [comment]
Make sure the filename you are uploading doesn't contain spaces.

**Comment by Bharath-2656** [comment]
Thanks, that fixed it. Could you please mention it in README file or rename the file and remove spaces before uploading to S3.

**Comment by pbv0** [comment]
Now fixed e8a5cbf
